GRPCServer:
  AppVersion: 1.0.0
  Port: ":5003"
  CookieLifeTime: 360
  CsrfExpire: 15
  SessionExpire: 60
  SessionID: "SessionID"
  Mode: "Development"
  Timeout: 15
  ReadTimeout: 5
  WriteTimeout: 5
  MaxConnectionIdle: 5
  MaxConnectionAge: 5
  SessionPrefix: "session"
  CSRFPrefix: "csrf"
  SessionGrpcServicePort: ":5000"

Kafka:
#  Brokers: ["kafka1:9093", "kafka2:9093", "kafka3:9093"]
  Brokers: ["localhost:9092", "localhost:9092", "localhost:9092"]
#  Brokers: ["host.docker.internal:9093", "host.docker.internal:9093", "host.docker.internal:9093"]

HttpServer:
  Port: ":8007"
  PprofPort: ":8100"
  Timeout: 15
  ReadTimeout: 5
  WriteTimeout: 5
  CookieLifeTime: 44640
  SessionCookieName: "session_token"

postgres:
  PostgresqlHost: monorail.proxy.rlwy.net
  PostgresqlPort: 23962
  PostgresqlUser: postgres
  PostgresqlPassword: wEkkDLzNNjGUuecxUqAHUizVVchCvBhX
  PostgresqlDbname: railway
  PostgresqlSslmode: "disable"
  PgDriver: pgx

logger:
  Development: true
  DisableCaller: false
  DisableStacktrace: false
  Encoding: json
  Level: info


redis:
  RedisAddr: localhost:6379
  RedisPassword:
  RedisDb: 0
  RedisDefaultDB: 0
  MinIdleConn: 200
  PoolSize: 12000
  PoolTimeout: 240
  Password: ""
  DB: 0

metrics:
  Port: ":7073"
  Url: 0.0.0.0:7073
  ServiceName: hotels_microservice

jaeger:
  Host: localhost:6831
  ServiceName: HotelsService_GRPC
  LogSpans: false
